language: csharp
solution: src\Profiler.sln
mono: none
dotnet: 2.2
script:
  - cd src
  - dotnet restore
  - dotnet build
  - cd Profiler.UnitTests
  - dotnet test
  - cd ../Profiler.FuzzingTests
  - dotnet test
