language: csharp
solution: src\Profiler.sln
mono: none
dotnet: 2.2
script:
  - cd src
  - dotnet restore
  - dotnet build -c Release
  - cd Profiler.UnitTests
  - dotnet test -c Release
  - cd ../Profiler.FuzzingTests
  - dotnet test -c Release
  - cd ../Profiler.PerformanceTests
  - dotnet test -c Release 
